services:
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    restart: always
    links:
      - "backend"
      - "adminer"
      - "keycloak"
    environment:
      - TZ=${TZ}
    ports:
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./front/dist:/usr/share/nginx/html
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    expose:
      - 8080
  backend:
    image: magm3333/tomcat-jdk21:10.1.44
    container_name: backend
    restart: always
    environment:
      - TZ=${TZ}
    depends_on:
      - mysql
    expose:
      - 8080
    volumes:
      - ./tomcat/webapps:/opt/tomcat/webapps
      - ./tomcat/conf/catalina.properties:/opt/tomcat/conf/catalina.properties
      - ./tomcat/bin/setenv.sh:/opt/tomcat/bin/setenv.sh
      - /etc/localtime:/etc/localtime:ro
  mysql:
    image: mysql:8.0.43
    container_name: mysql_iw3
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLROOTPWD}
      - MYSQL_USER=user
      - MYSQL_PASSWORD=${MYSQLPWD}
      - TZ=${TZ}
    expose:
      - 3306
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_0900_ai_ci",
      "--default-authentication-plugin=mysql_native_password"
    ]
    volumes:
      - mysql-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - ./mysqlinit:/docker-entrypoint-initdb.d
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    expose:
      - 8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_PROXY: edge
      KC_HOSTNAME: auth.cernikiw3.chickenkiller.com
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    volumes:
      - keycloak_data:/opt/keycloak/data
    restart: unless-stopped
volumes:
  mysql-data:
  keycloak_data:
